version: 2

updates:
  - package-ecosystem: npm
    schedule:
      interval: weekly
    directory: /
    labels:
      - dependencies

  - package-ecosystem: docker
    schedule:
      interval: weekly
    directory: /
    labels:
      - dependencies

  - package-ecosystem: github-actions
    schedule:
      interval: weekly
    directory: /
    labels:
      - ci
